### ISSUE TITLE
undefined: strings.Builder

### ISSUE THREAD

**Issue by jremond** [coredns/coredns#2368]
Hello,

When trying to build tag v1.2.6 with go version go1.9.4 linux/amd64
I have the error message : undefined: strings.Builder

Seems like it's only available from go 1.10
https://stackoverflow.com/questions/48978414/golang-strings-builder-type-undefined

../../miekg/dns/dnssec_keyscan.go:295:7: undefined: strings.Builder
../../miekg/dns/msg_helpers.go:270:8: undefined: strings.Builder
../../miekg/dns/serve_mux.go:43:9: undefined: strings.Builder
../../miekg/dns/types.go:424:10: undefined: strings.Builder
../../miekg/dns/types.go:448:10: undefined: strings.Builder
../../miekg/dns/types.go:476:10: undefined: strings.Builder
../../miekg/dns/types.go:497:29: undefined: strings.Builder
../../miekg/dns/types.go:507:28: undefined: strings.Builder

Does it mean coredns now require go1.10 ?
From the main README.md :

`Some of the dependencies require Go version 1.9 or later.
`

It works fine with 1.11.2.

Thanks

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] undefined: string..." ]
>Hello,
>
>When trying to build tag v1.2.6 with go version go1.9.4 linux/amd64
>I have the error message : undefined: strings.Builder
>
>Seems like it's only available from go 1.10
>https://stackoverflow.com/questions/48978414/golang-strings-builder-type-undefined
>
>../../miekg/dns/dnssec_keyscan.go:295:7: undefined: strings.Builder
>../../miekg/dns/msg_helpers.go:270:8: undefined: strings.Builder
>../../miekg/dns/serve_mux.go:43:9: undefined: strings.Builder
>../../miekg/dns/types.go:424:10: undefined: strings.Builder
>../../miekg/dns/types.go:448:10: undefined: strings.Builder
>../../miekg/dns/types.go:476:10: undefined: strings.Builder
>../../miekg/dns/types.go:497:29: undefined: strings.Builder
>../../miekg/dns/types.go:507:28: undefined: strings.Builder
>
>Does it mean coredns now require go1.10 ?

Yes.
