### ISSUE TITLE
Module dependency out of date in relation to code being used

### ISSUE THREAD

**Issue by snebel29** [coredns/coredns#7731]
**What happened**:

Failing checks in https://github.com/coredns/coredns/pull/7728 due to module dependency version mismatch, see [Circle-CI logs](https://app.circleci.com/pipelines/github/coredns/coredns/9869/workflows/6168c48a-02b6-4031-ba83-2383b1cca2a3/jobs/9915/steps).

`Run Kubernetes tests` check fail with following error:

```console
# github.com/coredns/ci/test/kubernetes [github.com/coredns/ci/test/kubernetes.test]
./metrics_test.go:87:15: undefined: expfmt.NewTextParser
FAIL    github.com/coredns/ci/test/kubernetes [build failed]
FAIL
```

**What you expected to happen**:

It should pass.

**How to reproduce it (as minimally and precisely as possible)**:

Create a change into a PR in https://github.com/coredns/coredns and see that check failing (This seems to not fail systematically).

**Anything else we need to know?**:

Either update all dependencies in https://github.com/coredns/ci or revert https://github.com/coredns/ci/pull/165 by using [var tp expfmt.TextParser](https://github.com/coredns/ci/commit/dde8c112e9c7611ef524b2c9d7d9fce25ef599d2) instead of [expfmt.NewTextParser](https://github.com/prometheus/common/blob/d80d8544703e59a080a204b6f7429ac6561fb24f/expfmt/text_parse.go#L89).

Also, Consider adding comprehensive testing to https://github.com/coredns/ci

**Environment**:

N/A

**Comment by snebel29** [comment]
Interestingly enough I haven't found the issue during https://github.com/coredns/coredns/pull/7730 besides [logs](https://app.circleci.com/pipelines/github/coredns/coredns/9875/workflows/e8be8582-c316-4b52-84e5-6f8f8a3c0e93/jobs/9921) suggesting it pulling `v0.59.1` and current `HEAD` of the `coredns/ci` repo leveraging `expfmt.NewTextParser`, [see](https://github.com/coredns/ci/blob/baaf458ce417d08051120d60df976627d25e02cc/test/kubernetes/metrics_test.go#L87).

```text
go: downloading github.com/prometheus/common v0.59.1
``` 
And which does not implement `expfmt.NewTextParser` until `v0.66.0`.

- https://github.com/prometheus/common/blob/v0.59.1/expfmt/text_parse.go
- https://github.com/prometheus/common/blob/v0.66.0/expfmt/text_parse.go

**Comment by snebel29** [comment]
[Last Circle-CI job](https://app.circleci.com/pipelines/github/coredns/coredns/9882/workflows/0f144f6e-0b08-4362-86fe-f0cbcaf7e4ef/jobs/9928) check run of https://github.com/coredns/coredns/pull/7728 was successful, I do wonder what may have happened.
